<a href="https://colab.research.google.com/github/Ice-CreamAT/StandarlizationKNN/blob/main/StandarlizationKNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***STANDARLIZATION (AND KNN)***

##- The idea of ​​this project is based on a data processing experiment. The classification algorithm used was KNN.

## - As an example, I used a database prepared by Kaggle to carry out the experiment.
* More information about KNN in [K-Nearest Neighbors Algorithm](https://www.ibm.com/topics/knn)

In [22]:
import pandas as pd  # Read the database
import numpy as np   # Show statistical attributes
dataset = pd.read_csv("/content/credit_data.csv")
dataset.dropna(inplace=True)
dataset.head()

clientid        income        age         loan  default
0         1  66155.925095  59.017015  8106.532131        0
1         2  34415.153966  48.117153  6564.745018        0
2         3  57317.170063  63.108049  8020.953296        0
3         4  42709.534201  45.751972  6103.642260        0
4         5  66952.688845  18.584336  8770.099235        1

# ***NO STANDARLIZATION - 84%***

In [23]:
from sklearn.neighbors import KNeighborsClassifier   # The classifier that will be used (KNN)
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split # Used to divide a dataset into training and testing sets

In [24]:
X = dataset.iloc[:, 1:4].values
X

array([[6.61559251e+04, 5.90170151e+01, 8.10653213e+03],
       [3.44151540e+04, 4.81171531e+01, 6.56474502e+03],
       [5.73171701e+04, 6.31080495e+01, 8.02095330e+03],
       ...,
       [4.43114493e+04, 2.80171669e+01, 5.52278669e+03],
       [4.37560566e+04, 6.39717958e+01, 1.62272260e+03],
       [6.94365796e+04, 5.61526170e+01, 7.37883360e+03]])

In [25]:
Y = dataset['default'].values
Y

array([0, 0, 0, ..., 1, 0, 0])

In [26]:
X_training, X_test, Y_training, Y_test = train_test_split(X, Y, test_size=0.2,
                                                          stratify = Y)

In [27]:
np.mean(X_training[0]), np.median(X_training[0]), np.std(X_training[0])

(16092.07528047009, 6993.04944148178, 18018.04893222562)

In [28]:
np.mean(X_test[0]), np.median(X_test[0]), np.std(X_test[0])

(16494.337731779033, 599.347887026431, 22860.67571398028)

In [29]:
knn = KNeighborsClassifier()
knn.fit(X_training, Y_training)

KNeighborsClassifier()

In [30]:
predicts = knn.predict(X_test)

In [31]:
accuracy_score(Y_test, predicts)

0.8425

# ***WITH STANDARLIZATION - 98%***

In [32]:
from sklearn.preprocessing import StandardScaler # Used to standardize dataset characteristics

In [33]:
z_score_training = StandardScaler()
z_score_test = StandardScaler()

In [34]:
X_training_p = z_score_training.fit_transform(X_training)
X_test_p = z_score_test.fit_transform(X_test)

In [35]:
X_training_p, X_test_p

(array([[-0.28702035, -0.87983896,  0.83246822],
        [ 0.46146528, -0.40554803,  0.58541959],
        [-0.73768501,  1.28644052, -1.32487381],
        ...,
        [-1.72625567, -0.92687156, -0.38057928],
        [ 1.23222889,  1.14556722, -0.49699857],
        [ 0.07500993, -0.88733715, -0.98200692]]),
 array([[ 0.25358998,  1.52722862, -1.22045209],
        [-1.4662365 , -0.18484001, -0.69340193],
        [ 0.37335408,  1.20882535, -1.37657498],
        ...,
        [ 0.29493197, -1.59506506, -0.58683392],
        [ 0.74787181, -0.95117814, -1.09882545],
        [ 0.93784222,  0.9620455 , -0.57566822]]))

In [36]:
min(X_training_p[0]), max(X_training_p[0])

(-0.8798389587216568, 0.8324682191727832)

In [37]:
np.mean(X_training_p), np.median(X_training_p), np.std(X_training_p)

(-2.8297130866839307e-15, -0.04090043161919967, 0.9999999999999998)

In [38]:
np.mean(X_test_p), np.median(X_test_p), np.std(X_test_p)

(1.0954200509634878e-16, -0.021358837930160947, 0.9999999999999999)

In [39]:
knn = KNeighborsClassifier()
knn.fit(X_training_p, Y_training)
predicts = knn.predict(X_test_p)
accuracy_score(Y_test, predicts)

0.9825